ALTER TABLE `settings` ADD `r1_feasability_study_status` VARCHAR( 200 ) NULL ,
ADD `r1_feasability_study_cmt` TEXT NULL ,
ADD `r1_p2_status` VARCHAR( 200 ) NULL ,
ADD `r1_p2_cmt` TEXT NULL ,
ADD `r1_p3_status` VARCHAR( 200 ) NULL ,
ADD `r1_p3_cmt` TEXT NULL ,
ADD `r1_p4_status` VARCHAR( 200 ) NULL ,
ADD `r1_p4_cmt` TEXT NULL ,
ADD `r1_p5_status` VARCHAR( 200 ) NULL ,
ADD `r1_p5_cmt` TEXT NULL ,
ADD `r1_p6_status` VARCHAR( 200 ) NULL ,
ADD `r1_p6_cmt` TEXT NULL ,
ADD `r1_p7_status` VARCHAR( 200 ) NULL ,
ADD `r1_p7_cmt` TEXT NULL ;
ALTER TABLE `settings` ADD `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST ;